encoding: UTF-8

permalink: /:year/:month/:day/:title.html
paginate: 5
markdown: kramdown

kramdown:
  input: GFM

highlighter: rouge


# 作者信息
author: 
  name: 王野
  email: itwangye@163.com
  link: https://wangye8899.github.io/
  github: https://github.com/wangye8899
  github_username:  wangye8899

# 站点信息
title : WangYe's Home
description: 
  一不小心迈入计算机行业，在程序猿的道路上艰难地前行，目标是成
  为一名优秀的全栈工程师或者说资深码农。对很多东西都充满兴趣，
  跑步游泳，近期目标是能跑半程马拉松，学会自由泳。
url: https://wangye8899.github.io/
rss_url: /feed.xml

# gavatar头像及Favicon
gavatar : /assets/img/gavatar.png
favicon : /assets/img/favicon.png

# disqus 设置
#disqus:
#  shortname: blademastercoder

#profile 个人信息

profile_desc : DarLie<br>Java Developer<br>

# 首页除了最新文章外显示分类
cates: 
- Essay

# 中文本地化
locals: 
   newest : 最新文章